### ISSUE TITLE
Windows 8: --locally command doesn't work - The system cannot find the file specified

### ISSUE THREAD

**Issue by RichStone** [RichStone/mareposa#1]
```
Traceback (most recent call last):
  File "C:\Python37\Scripts\mareposa-script.py", line 11, in <module>
    load_entry_point('mareposa==1.0.1', 'console_scripts', 'mareposa')()
  File "c:\python37\lib\site-packages\click\core.py", line 764, in __call_
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\mareposa\cli.py", line 51, in create
    ['git', 'commit', '-m"start project"']
  File "c:\python37\lib\site-packages\mareposa\cli.py", line 68, in bash_e
    process = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "c:\python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by RichStone** [comment]
git was not installed
